# File: .github/workflows/lint-markdown.yml
---

name: Shared Lint Markdown Workflow

on: # yamllint disable-line rule:truthy
    pull_request:
        branches:
            - main

jobs:
    lint-markdown:
        name: Lint Markdown
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4  # Checkout the calling repo

            - name: Checkout shared config
              uses: actions/checkout@v4
              with:
                repository: brixion/.github
                path: shared
                sparse-checkout: |
                  .github/workflows/configs/.markdownlint.yaml
                sparse-checkout-cone-mode: false

            - name: Copy markdownlint config
              run: |
                if [ -f .github/workflows/configs/.markdownlint.yaml ]; then
                  cp .github/workflows/configs/.markdownlint.yaml .markdownlint.yaml
                else
                  cp shared/.github/workflows/configs/.markdownlint.yaml .markdownlint.yaml
                fi

            - name: Lint Markdown
              uses: DavidAnson/markdownlint-cli2-action@v19
              with:
                globs: |
                  **/*.md
                  !shared/**